#### Question-1 How is shape of ndarray stored? (Tuple/List/ndarray object?)

In [ ]:
Tuple object

In [2]:
import numpy as np

#### Question-2 Create a 3D Matrix by all the possible methods you know

In [36]:
arr=np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Question-3 Print The Remaining Elements here

In [37]:
arr = [[1,2,3],[3,4,5],[5,6,7]]
arr2 = np.array(arr)

for i in range(3):
    for j in range(3):
        print(arr2[i,j])

1
2
3
3
4
5
5
6
7


#### Question-4 Print a Descending Array of counting tuning the parameters in the arange method EX: [100,99,98......

In [12]:
arr1=np.arange(100,0,-1)
print(arr1)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


#### Question-5 Create a 3D Array using arange function

In [13]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Question-6 What's the difference between arr_back and arr_back_2?

In [ ]:
shape

#### Question-7 Create a 3D array and try to select more than one element in it notice any difference?

In [22]:
arr3=np.arange(9).reshape(3,3)
print(arr3[1,:2])

[3 4]


#### Question-8 Explore Deep Stacking and Column Stacking

In [26]:
#deep stacking
a1=np.arange(9).reshape(3,3)
a2=np.arange(9).reshape(3,3)
np.dstack((a1,a2))

#coloumn stack - 1d arrays to 2d arrays
b1=np.array([1,2,3])
b2=np.array([4,5,6])
np.column_stack((b1,b2))


array([[1, 4],
       [2, 5],
       [3, 6]])

#### Question-9 Explore The Opposite of Stacking - Splitting

In [29]:
#split - used to divide an array into multiple subarrays 
np1=np.arange(16).reshape(2,2,4)
print(np.dsplit(np1,2))

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]