#### Question-1 How is shape of ndarray stored? (Tuple/List/ndarray object?)

In [1]:
import numpy as np
np.ndarray.shape

<attribute 'shape' of 'numpy.ndarray' objects>

#### Question-2 Create a 3D Matrix by all the possible methods you know

In [6]:
np.full([3,3],6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [10]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
x=[[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.random.random((3,3))

array([[0.64029389, 0.51502821, 0.52676162],
       [0.04674886, 0.66116611, 0.10081713],
       [0.54618054, 0.11232918, 0.79972539]])

In [23]:
np.empty((3,3))

array([[0.64029389, 0.51502821, 0.52676162],
       [0.04674886, 0.66116611, 0.10081713],
       [0.54618054, 0.11232918, 0.79972539]])

In [26]:
import numpy as np
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Question-3 Print The Remaining Elements here

In [8]:
import numpy as np
arr=np.arange(9).reshape(3,3)
print(arr[0,2])
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])
print(arr[2,0])
print(arr[2,1])
print(arr[2,2])

2
3
4
5
6
7
8


#### Question-4 Print a Descending Array of counting tuning the parameters in the arange method EX: [100,99,98......

In [19]:
import numpy as np
x=np.arange(100,0,-1)
x

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

#### Question-5 Create a 3D Array using arange function

In [30]:
import numpy as np
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Question-6 What's the difference between arr_back and arr_back_2?

In [31]:
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Question-7 Create a 3D array and try to select more than one element in it notice any difference?

In [4]:
import numpy as np
arr=np.arange(9).reshape(3,3)
print(arr[0:1])

[[0 1 2]]


#### Question-8 Explore Deep Stacking and Column Stacking

In [6]:
#horizontal stacking
import numpy as np
a=np.arange(9).reshape(3,3)
b=a**2
concat1= np.concatenate((a,b),axis=1)
concat1

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25],
       [ 6,  7,  8, 36, 49, 64]])

In [7]:
#horizontal stacking
import numpy as np
a=np.arange(9).reshape(3,3)
b=a**2
concat2= np.concatenate((a,b),axis=0)
concat2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

#### Question-9 Explore The Opposite of Stacking - Splitting

In [9]:
x=np.arange(6)
np.split(x,3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [15]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
#vertical splitting
a=np.arange(16).reshape(4,4)   
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [17]:
#horizontall splitting
a=np.arange(16).reshape(4,4)
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]