#### Question-1 How is shape of ndarray stored? (Tuple/List/ndarray object?)

In [ ]:
Tuple

#### Question-2 Create a 3D Matrix by all the possible methods you know

In [1]:
import numpy as np
vals_3d=[[[2,3,2,5],[6,4,8,1]],[[8,5,2,7],[3,5,1,6]]]
np_vals_3d=np.array(vals_3d)
np_vals_3d

array([[[2, 3, 2, 5],
        [6, 4, 8, 1]],

       [[8, 5, 2, 7],
        [3, 5, 1, 6]]])

#### Question-3 Print The Remaining Elements here

In [7]:
vals = [1,2,3,4,5]
np_vals = np.array(vals)

vals_2d = [[1,2,3],[3,4,5],[5,6,7]]
np_vals_2d = np.array(vals_2d)

print(np_vals[0])
print(np_vals[1])
print(np_vals[3])
print(np_vals[4])
print(np_vals_2d[0,2])
print(np_vals_2d[1,0])
print(np_vals_2d[1,1])
print(np_vals_2d[1,2])
print(np_vals_2d[2,0])
print(np_vals_2d[2,1])
print(np_vals_2d[2,2])




1
2
4
5
3
3
4
5
5
6
7


#### Question-4 Print a Descending Array of counting tuning the parameters in the arange method EX: [100,99,98......

In [6]:
counting = np.arange(100,0,-1) 
counting

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

#### Question-5 Create a 3D Array using arange function

In [5]:
arr=np.arange(16)
arr.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

#### Question-6 What's the difference between arr_back and arr_back_2?

arr_back has 1 row and 10 columns and arr_back_2 has 10 rows and 1 column. 

#### Question-7 Create a 3D array and try to select more than one element in it notice any difference?

In [7]:
vals_3d=[[[2,3,2,5],[6,4,8,1]],[[8,5,2,7],[3,5,1,6]]]
np_vals_3d=np.array(vals_3d)
np_vals_3d[0,:,:]
#Here the elements having their 1st dimension 0 will be printed

np_vals_3d[:,0,:]
#Here the elements having their second dimension 0 will be printed

array([[2, 3, 2, 5],
       [8, 5, 2, 7]])

#### Question-8 Explore Deep Stacking and Column Stacking

In [12]:
#deep stack-->a & b are 2-D array
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.dstack((a,b)) #It'Ll be converted to 3-D 


array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

In [11]:
#column stack-->returns a 2-D array
a=np.array([1,2,3])
b=np.array([5,6,7])
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7]])

#### Question-9 Explore The Opposite of Stacking - Splitting

In [14]:
a=np.array([1,2,3,4,5,6])
np.split(a,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [19]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
np.hsplit(a,2) #horizontal splitting

[array([[1],
        [3],
        [5],
        [7]]), array([[2],
        [4],
        [6],
        [8]])]

In [18]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
np.vsplit(a,2) #vertical splitting

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]])]