#### Question-1 How is shape of ndarray stored? (Tuple/List/ndarray object?)

In [1]:
Tuple object

#### Question-2 Create a 3D Matrix by all the possible methods you know

In [8]:
import numpy as np
matrix_3d=[[1,2,3],[3,4,5],[5,6,7]]
matrixnp_3d=np.array([[1,2,3],[3,4,5],[5,6,7]])

#### Question-3 Print The Remaining Elementshere

In [9]:
for x in range(3):
    for y in range(3):
        print(matrixnp_3d[x][y])

1
2
3
3
4
5
5
6
7


#### Question-4 Print a Descending Array of counting tuning the parameters in the arange method EX: [100,99,98......

In [11]:
arr=np.arange(10,0,-1)
print(arr)

[10  9  8  7  6  5  4  3  2  1]


#### Question-5 Create a 3D Array using arange function

In [14]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Question-6 What's the difference between arr_back and arr_back_2?

In [ ]:
shape

#### Question-7 Create a 3D array and try to select more than one element in it notice any difference?

In [17]:
threeD_array=np.arange(9).reshape(3,3)
threeD_array[1,:]

array([3, 4, 5])

#### Question-8 Explore Deep Stacking and Column Stacking

In [23]:
array1=np.arange(9).reshape(3,3)
array2=np.arange(9).reshape(3,3)
np.dstack((array1,array2))

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]],

       [[6, 6],
        [7, 7],
        [8, 8]]])

#### Question-9 Explore The Opposite of Stacking - Splitting

In [31]:
np.dsplit(np.arange(12).reshape(3,2,2),2)


[array([[[ 0],
         [ 2]],
 
        [[ 4],
         [ 6]],
 
        [[ 8],
         [10]]]), array([[[ 1],
         [ 3]],
 
        [[ 5],
         [ 7]],
 
        [[ 9],
         [11]]])]