In [3]:
import numpy as np


How is shape of ndarray stored? (Tuple/List/ndarray object?)

In [4]:
np.ndarray.shape

<attribute 'shape' of 'numpy.ndarray' objects>

Create a 3D Matrix by all the possible methods you know

In [5]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
vals_2d = [[1,2,3],[3,4,5],[5,6,7]]
print(vals_2d)

[[1, 2, 3], [3, 4, 5], [5, 6, 7]]


In [7]:
#using linspace
nx, ny = (3, 2)
x1 = np.linspace(0, 1, nx)
y1 = np.linspace(0, 1, ny) 
xv, yv = np.meshgrid(x1, y1)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.random.random((3,3))

array([[0.9171977 , 0.33914556, 0.46643298],
       [0.93669283, 0.20977395, 0.13263452],
       [0.53714211, 0.83118224, 0.36044908]])

In [11]:
np.empty((3,3))

array([[0.9171977 , 0.33914556, 0.46643298],
       [0.93669283, 0.20977395, 0.13263452],
       [0.53714211, 0.83118224, 0.36044908]])

In [12]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


Print The Remaining Elements here

In [13]:

print(array[0,2])
print(array[1,0])
print(array[1,1])
print(array[1,2])
print(array[2,0])
print(array[2,1])
print(array[2,2])

2
3
4
5
6
7
8


Print a Descending Array of counting tuning the parameters in the arange method EX: [100,99,98......

In [14]:
counting=np.arange(100, 0, -1)
print(counting)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


Create a 3D Array using arange function

In [15]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

What's the difference between arr_back and arr_back_2

In [16]:
arr = np.arange(10)
arr_2d = arr.reshape(2,5)

In [17]:
#this means matrix of 1,10 is created(default it makes 1d array )
arr_back = arr_2d.reshape(10) 
arr_back


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#this means matrix of 10,1 is created(here 2d matrix)
arr_back_2 = arr_2d.reshape(10,1)
arr_back_2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Create a 3D array and try to select more than one element in it notice any difference

In [19]:
a = np.arange(9).reshape(3,3)
print(a)
a[1:2]#selecting multiple elements 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5]])

Explore Deep Stacking and Column Stacking

In [20]:
#horizontal stacking
b=a*2
concat_h = np.concatenate((a,b),axis=1) #<------- 1 Means Horizontal or along x axis by defualt
concat_h


array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [21]:
#vertical stacking
concat_v = np.concatenate((a,b),axis=0) #<------- 1 Means Horizontal or along x axis by defualt
concat_v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Explore The Opposite of Stacking - Splitting

In [22]:
 x = np.arange(9)
print(x)
np.split(x, 3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [23]:
y=np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.vsplit(y, 2)#splits rowwise

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [25]:
np.hsplit(y, 2)#splits columnwise

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]