# Numpy Worksheet - 1

## __What is Numpy?__

#### NumPy (from Numerical Python) is an open-source Python library for scientific computing.NumPy let's you work with arrays and matrices in a natural way. The library contains a long list of useful mathematical functions including some for linear algebra, Fourier transformation, and random number generation routines.

## __Why Numpy?__

#### NumPy code is much cleaner than "straight" Python code that tries to accomplish the same task. There are less loops required, because operations work directly on arrays and matrices.The many convenience and mathematical functions make life easier as well. The underlying algorithms have stood the test of time and have been designed with high performance in mind.

## Section-1 Creating Numpy Array

In [6]:
#first import numpy package
import numpy as np

In [7]:
vals = [1,2,3,4,5]
np_vals = np.array(vals)
np_vals #<----------------------------------- Prefix array before the print below

array([1, 2, 3, 4, 5])

In [8]:
print(type(np_vals)) #<---------------------- Numpy arrays are ndarray type objects

<class 'numpy.ndarray'>


In [9]:
#Finding the dimensions of array
print(np_vals.shape)

(5,)


In [10]:
#Doing the same process with a 2-D Array
vals_2d = [[1,2,3],[3,4,5],[5,6,7]]
np_vals_2d = np.array(vals_2d)
np_vals_2d #<===================================== Output comes in clear and concise form. It made a 2D array display as matrix

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [11]:
print(type(np_vals_2d))

<class 'numpy.ndarray'>


In [12]:
print(np_vals_2d.shape) #<======================= Clear and Cut

(3, 3)


## Section-2 Selecting an element

#### Selecting is a very much needed function. Sometimes you don't work with full array you just to have work with some elements that's where selection is helpful.

### __How it works?__
1. Format : arrayname[index_num]
2. For 2D Array Format: arrayname[row_num,col_num]

In [27]:
#We have two previous numpy arrays
#np_vals and np_vals_2d

In [13]:
#printing the third element in the np_vals
print(np_vals[2]) #,----------------- Index starts at 0

3


In [14]:
#printing the first element in np_vals_2d that is first row and first column's intersection
print(np_vals_2d[0,0])
print(np_vals_2d[0,1]) #----> To print next element within the same row change the column number by one

1
2


In [17]:
#Can you print the remaining elements in the Numpy Worksheet-1? (Question-3)
for i in range(3):
    for k in range(3):
        print(np_vals_2d[i,k])

1
2
3
3
4
5
5
6
7


## Numpy Data Types
* bool Boolean (True or False) stored as a bit
* inti Platform integer (normally either int32 or int64)
* int8 Byte (-128 to 127)
* int16 Integer (-32768 to 32767)
* int32 Integer (-2 ** 31 to 2 ** 31 -1)
* int64 Integer (-2 ** 63 to 2 ** 63 -1)
* uint8 Unsigned integer (0 to 255)
* uint16 Unsigned integer (0 to 65535)
* uint32 Unsigned integer (0 to 2 ** 32 - 1)
* uint64 Unsigned integer (0 to 2 ** 64 - 1)
* float16 Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
* float32 Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
* float64 or float Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
* complex64 Complex number, represented by two 32-bit floats (real and imaginary components)
* complex128 or complex Complex number, represented by two 64-bit floats (real and imaginary components)

In [20]:
np.float64(42)

42.0

In [19]:
np.int8(42.0)

42

In [23]:
np.bool(41)

True

In [22]:
np.bool(0)

False

In [43]:
np.bool(42.0)

True

In [24]:
np.float(True)

1.0

In [45]:
np.float(False)

0.0

# Creating Numpy Array Cool Way
__np.arange(start,stop,step)__

start -> Number from which u want to start the range

stop -> Number on which the range is stopped

step -> Means the common difference how much of a jump after each number (start+step = next term)__


ALTERNATIVELY

__np.arange(stop)__
by defualt => start = 0, step=1

In [52]:
counting = np.arange(1,100,1) 
print(counting) #You can get the idea of it

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


### Trying varying the third argument in the arange function and observe the changes

### Head to Question 4 and 5 for this topic pratice

## Reshaping The Array

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.reshape(rows,cols)
__make sure when you use that to reshape your np array there is one thing perfectly the number of elements in the pre converted array must be a multiple of no of rows and no of columns you want in your new array otherwise conversion fails__

In [66]:
arr.reshape(5,2) #<------------------- 5 Rows and 2 Columns

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
arr.reshape(2,5) #<-------------------- 2 Rows and 5 Columns

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr_2d = arr.reshape(2,5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
arr_back = arr_2d.reshape(10) #<------------------- This is how you have to convert it back 10 rows
arr_back

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr_back_2 = arr_2d.reshape(10,1) #<------------------- This is how you have to convert it back 10 rows
arr_back_2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### Head to Question - 6

### Selecting More than One Element

In [79]:
## Selecting more than one element
arr = np.arange(20)
arr[0] 

0

In [81]:
arr[0:5] #<============== Colon selects the index upto which u mention(last index is excluded)

array([0, 1, 2, 3, 4])

In [97]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
#Selecting first row elements
arr_2d[0, :] #<---------- ':' means Select everything : So this fixes the row to 0 and selects every value of columns colliding with that row

array([1, 2, 3])

In [99]:
#Selecting the first column elements
arr_2d[:, 0] #<------------ Same Drill Select all rows but fix col = 0 so [0,0],[1,0],[2,0] elements are selected

array([1, 4, 7])

In [100]:
#Head to notebook for Questions

### Ravel: We can accomplish this with the ravel function:

In [103]:
b = np.array([[[ 0, 1, 2, 3],[ 4, 5, 6, 7],[ 8, 9, 10, 11]],[[12, 13, 14, 15],[16, 17, 18, 19],[20, 21, 22, 23]]])
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Flatten: The appropriately-named function, flatten, does the same as ravel,

In [105]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Transposing

In [110]:
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print(b)

[[1 4]
 [2 5]
 [3 6]]


### Stacking of Array

In [112]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a**2

In [113]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [118]:
c = np.hstack((a,b))
c

array([[ 1,  2,  3,  1,  4,  9],
       [ 4,  5,  6, 16, 25, 36],
       [ 7,  8,  9, 49, 64, 81]])

In [119]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Concatenation - Same thing with one extra parameter

In [124]:
concat_h = np.concatenate((a,b),axis=1) #<------- 1 Means Horizontal or along x axis by defualt
concat_h

array([[ 1,  2,  3,  1,  4,  9],
       [ 4,  5,  6, 16, 25, 36],
       [ 7,  8,  9, 49, 64, 81]])

In [126]:
concat_v = np.concatenate((a,b),axis=0) #<------- 0 Means Vertical or along y axis by defualt
concat_v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [127]:
# Head out to answer some Questions

### Some Other Available Functions

In [131]:
b_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [132]:
b_2d.ndim

2

In [133]:
b_2d.size

9

In [135]:
b_2d.itemsize

8

In [136]:
#total size of array
b_2d.size * b_2d.itemsize

72

In [137]:
b.dtype

dtype('int64')

In [142]:
b_complex = np.array([[1+2j,2+3j],[3+4j,4+5j]])

In [143]:
b_complex

array([[1.+2.j, 2.+3.j],
       [3.+4.j, 4.+5.j]])

In [144]:
b_complex.dtype

dtype('complex128')

In [145]:
b_complex.size

4

In [146]:
b_complex.itemsize

16

In [147]:
b_complex.size * b_complex.itemsize

64

### Going Back to Land Down Under

In [148]:
#Coversion to list type
b_list = b_2d.tolist()

In [149]:
b_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [150]:
type(b_list)

list

In [151]:
b_complex_list = b_complex.tolist()

In [152]:
b_complex_list

[[(1+2j), (2+3j)], [(3+4j), (4+5j)]]

In [153]:
type(b_complex_list)

list