In [1]:
import numpy as np

### Ways to create Matrices

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
b = np.eye(3) #Create identity matrix (diagonal elements = 1 and otherwise 0 of the given dimension here 3*3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
only1 = np.ones((3,4))
only1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
only0 = np.zeros((3,4))
only0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
c = a+b 
c

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [8]:
d = a-b
d

array([[0., 2., 3.],
       [4., 4., 6.],
       [7., 8., 8.]])

### Dot Product and Cross product

In [20]:
ab_dot = np.dot(a,b)
ab_cross = np.cross(a,b)

In [21]:
ab_dot

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [22]:
ab_cross

array([[ 0.,  3., -2.],
       [-6.,  0.,  4.],
       [ 8., -7.,  0.]])

### Matrix Summations

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [25]:
print(a**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [26]:
print(a/4)

[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]
 [1.75 2.   2.25]]


In [30]:
a #<============= a isn't affected since we didn't actually store anything or override a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
print(np.sum(a,axis=0)) #Summation of each column

[12 15 18]


In [32]:
print(np.sum(a,axis=1)) #By defualt one is horizontal or along x axis

[ 6 15 24]


In [34]:
print(np.sum(a)) #Sum of complete matrix

45
